spring.datasource.url=jdbc:postgresql://postgres:5432/teste_tecnico
spring.datasource.username=dellavolpe
spring.datasource.password=dellavolpe
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect