jwt.public.key=classpath:public.key
jwt.private.key=file:${JWT_PRIVATE_KEY_PATH}



spring.application.name=user-management-api


spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true



spring.application.name=user-management-api

server.port=8081

spring.datasource.url=jdbc:postgresql://postgres:5432/teste_tecnico
spring.datasource.username=dellavolpe
spring.datasource.password=dellavolpe
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
